/**
 * Gamification_platform
 * The API will be use for the final assesment
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LevelResults } from './levelResults';

export interface FinalUserInformation { 
    idUsuario?: number;
    nombre?: string;
    apellido?: string;
    mail?: string;
    puntajeProm?: number;
    puntajeTot?: number;
    idNivel?: number;
    levelResultArray?: Array<LevelResults>;
}