/**
 * Gamification_platform
 * The API will be use for the final assesment
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Level { 
    idNivel?: number;
    descripcion?: string;
    fechaRecomendadaRealizacion?: string;
    cantidadPreguntas?: number;
    puntajeMaximo?: number;
    reintentos?: number;
    penalizacion?: number;
    cuestionarioDisponible?: boolean;
    creadoPor?: number;
    nombre?: string;
    apellido?: string;
    fechaCreacion?: string;
    idMateria?: number;
    unitList?: any;
}